---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-block-pvc22
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-rbd-sc
